[package]
name = "syncr"
version = "0.1.0"
authors = ["owen <owen@oms.sh>"]

[dependencies]
futures = "0.1.13"
tokio-core = "0.1.6"
tokio-io = "0.1.1"
tokio-service = "0.1.0"
tempdir = "0.3.5"
md5 = "0.3.4"
bytes = "0.4.3"
base64 = "0.5.2"
tokio-proto = "0.1"

